import React from 'react';

export default function Footer() {
  return (
    <footer>
      <div className="footer-top">
        <div className="logo">
          <span className="logo-dot"></span>
          KAELIX<span style={{ color: 'var(--text2)', fontWeight: 300 }}>.AI</span>
        </div>
        <div className="footer-links">
          <div className="footer-col">
            <h4>Studio</h4>
            <a href="#work">Work</a>
            <a href="#services">Services</a>
            <a href="#process">Process</a>
            <a href="#about">About</a>
          </div>
          <div className="footer-col">
            <h4>Connect</h4>
            <a href="#">Instagram</a>
            <a href="#">X / Twitter</a>
            <a href="#">LinkedIn</a>
          </div>
          <div className="footer-col">
            <h4>Contact</h4>
            <a href="mailto:hello@kaelix.ai">hello@kaelix.ai</a>
          </div>
        </div>
      </div>
      <div className="footer-bottom">
        <span>© 2026 KAELIX.AI — All rights reserved.</span>
        <span>Generated by imagination.</span>
      </div>
    </footer>
  );
}
